# Generated by Django 2.2.6 on 2019-10-17 10:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=800)),
                ('salary', models.IntegerField()),
                ('listed_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('added', models.BooleanField(default=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruiters.Recruiter')),
            ],
        ),
    ]
